package com.example.starter_project_2025.domain.kanji_study.seed;

import com.example.starter_project_2025.domain.kanji_study.deck.KanjiDeck;
import com.example.starter_project_2025.domain.kanji_study.deck.KanjiDeckRepository;
import com.example.starter_project_2025.domain.kanji_study.deck_item.KanjiDeckItem;
import com.example.starter_project_2025.domain.kanji_study.deck_item.KanjiDeckItemRepository;
import com.example.starter_project_2025.domain.kanji_study.detail.KanjiDetail;
import com.example.starter_project_2025.domain.kanji_study.detail.KanjiDetailRepository;
import com.example.starter_project_2025.domain.kanji_study.radical.KanjiRadical;
import com.example.starter_project_2025.domain.kanji_study.radical.KanjiRadicalRepository;
import com.example.starter_project_2025.domain.kanji_study.reading.KanjiReading;
import com.example.starter_project_2025.domain.kanji_study.reading.KanjiReadingRepository;
import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.ObjectMapper;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.boot.CommandLineRunner;
import org.springframework.core.annotation.Order;
import org.springframework.core.io.ClassPathResource;
import org.springframework.stereotype.Component;
import org.springframework.transaction.annotation.Transactional;

import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * Seeds the self-contained Kanji Study tables (kanji_radicals, kanji_details, kanji_readings,
 * one built-in N5 deck) from {@code resources/seed/kanji-study-seed.json} on startup IF empty.
 *
 * Idempotent (skips when kanji_details already has rows) and resilient: if a restart recreates
 * the schema (e.g. ddl-auto drop), this repopulates automatically — no manual SQL needed.
 * Writes only Kanji-Study tables; never touches the Language `kanjis` table.
 *
 * Data file is regenerated by backend/scripts/gen-kanji-n5-seed.mjs.
 */
@Slf4j
@Component
@Order(50)
@RequiredArgsConstructor
public class KanjiStudyDataSeeder implements CommandLineRunner {

    private final KanjiRadicalRepository radicalRepository;
    private final KanjiDetailRepository detailRepository;
    private final KanjiReadingRepository readingRepository;
    private final KanjiDeckRepository deckRepository;
    private final KanjiDeckItemRepository deckItemRepository;
    private final ObjectMapper objectMapper;

    /** Default study-batch size: pre-made (system) decks come grouped 20 kanji per nhóm. */
    private static final int DEFAULT_GROUP_SIZE = 20;

    @Override
    @Transactional
    public void run(String... args) throws Exception {
        if (detailRepository.count() > 0) {
            backfillSystemDeckGroups();
            return; // already seeded
        }

        ClassPathResource resource = new ClassPathResource("seed/kanji-study-seed.json");
        if (!resource.exists()) {
            log.warn("Kanji Study seed file not found (seed/kanji-study-seed.json) — skipping seed.");
            return;
        }

        log.info("Seeding Kanji Study data...");
        JsonNode root = objectMapper.readTree(resource.getInputStream());

        // 1. Radicals (bộ thủ) — keep a number → entity map for linking.
        Map<Integer, KanjiRadical> byNumber = new HashMap<>();
        for (JsonNode r : root.path("radicals")) {
            KanjiRadical radical = radicalRepository.save(KanjiRadical.builder()
                    .number(r.path("number").asInt())
                    .character(text(r, "character"))
                    .hanViet(text(r, "hanViet"))
                    .meaning(text(r, "meaning"))
                    .strokeCount(intOrNull(r, "strokeCount"))
                    .build());
            byNumber.put(radical.getNumber(), radical);
        }

        // 2. Kanji master records + their Hán-Việt readings.
        // Keyed by character so the decks below can reference them.
        Map<String, KanjiDetail> byChar = new HashMap<>();
        for (JsonNode k : root.path("kanji")) {
            Integer radNum = intOrNull(k, "radicalNumber");
            KanjiDetail detail = detailRepository.save(KanjiDetail.builder()
                    .character(text(k, "character"))
                    .onyomi(text(k, "onyomi"))
                    .kunyomi(text(k, "kunyomi"))
                    .meaning(text(k, "meaning"))
                    .jlptLevel(text(k, "jlptLevel"))
                    .strokeCount(intOrNull(k, "strokeCount"))
                    .radical(radNum != null ? byNumber.get(radNum) : null)
                    .strokeData(text(k, "strokeData"))
                    .svgViewbox(text(k, "svgViewbox"))
                    .strokeSource(text(k, "strokeSource"))
                    .build());
            byChar.put(detail.getCharacter(), detail);

            int priority = 0;
            for (JsonNode hv : k.path("hanViet")) {
                readingRepository.save(KanjiReading.builder()
                        .kanji(detail)
                        .readingType("HAN_VIET")
                        .value(hv.asText())
                        .priority(priority++)
                        .build());
            }

            // Alternate-writing (cách viết khác) links.
            int vp = 0;
            for (JsonNode v : k.path("variants")) {
                readingRepository.save(KanjiReading.builder()
                        .kanji(detail)
                        .readingType("VARIANT")
                        .value(v.asText())
                        .priority(vp++)
                        .build());
            }
        }

        // 3. Built-in system decks (one per level: N5 + grades 1-3). A kanji shared
        //    across levels is referenced by every deck it belongs to.
        int deckCount = 0;
        for (JsonNode d : root.path("decks")) {
            KanjiDeck deck = deckRepository.save(KanjiDeck.builder()
                    .title(text(d, "title"))
                    .description(text(d, "description"))
                    .visibility("PUBLIC")
                    .isSystem(true)
                    .jlptLevel(text(d, "level"))
                    .totalKanji(d.path("characters").size())
                    .build());
            deckCount++;

            int order = 0;
            for (JsonNode c : d.path("characters")) {
                KanjiDetail detail = byChar.get(c.asText());
                if (detail == null) continue;
                deckItemRepository.save(KanjiDeckItem.builder()
                        .deck(deck)
                        .kanji(detail)
                        .groupIndex(order / DEFAULT_GROUP_SIZE)
                        .orderIndex(order++)
                        .build());
            }
        }

        log.info("Kanji Study seed complete: {} radicals, {} kanji, {} decks.",
                byNumber.size(), byChar.size(), deckCount);
    }

    /**
     * Databases seeded before group_index existed have every item in one flat group.
     * Re-chunk those system decks into the default 20-per-nhóm layout. Decks the user
     * already organised (more than one group) are left untouched.
     */
    private void backfillSystemDeckGroups() {
        for (KanjiDeck deck : deckRepository.findAll()) {
            if (!Boolean.TRUE.equals(deck.getIsSystem()) || Boolean.TRUE.equals(deck.getIsDeleted())) continue;

            List<KanjiDeckItem> items = deckItemRepository
                    .findByDeckIdAndIsDeletedFalseOrderByGroupIndexAscOrderIndexAsc(deck.getId());
            if (items.size() <= DEFAULT_GROUP_SIZE) continue;

            boolean flat = items.stream().allMatch(i -> i.getGroupIndex() == 0);
            if (!flat) continue;

            int order = 0;
            for (KanjiDeckItem item : items) {
                item.setGroupIndex(order / DEFAULT_GROUP_SIZE);
                item.setOrderIndex(order++);
            }
            deckItemRepository.saveAll(items);
            log.info("Kanji deck [{}] re-chunked into {} groups of {}.",
                    deck.getTitle(), (items.size() + DEFAULT_GROUP_SIZE - 1) / DEFAULT_GROUP_SIZE, DEFAULT_GROUP_SIZE);
        }
    }

    private static String text(JsonNode node, String field) {
        JsonNode v = node.path(field);
        return v.isMissingNode() || v.isNull() ? null : v.asText();
    }

    private static Integer intOrNull(JsonNode node, String field) {
        JsonNode v = node.path(field);
        return v.isMissingNode() || v.isNull() ? null : v.asInt();
    }
}
