package com.example.starter_project_2025.domain.kanji_study.seed;

import com.example.starter_project_2025.domain.kanji_study.deck.KanjiDeck;
import com.example.starter_project_2025.domain.kanji_study.deck.KanjiDeckRepository;
import com.example.starter_project_2025.domain.kanji_study.deck_item.KanjiDeckItem;
import com.example.starter_project_2025.domain.kanji_study.deck_item.KanjiDeckItemRepository;
import com.example.starter_project_2025.domain.kanji_study.detail.KanjiDetail;
import com.example.starter_project_2025.domain.kanji_study.detail.KanjiDetailRepository;
import com.example.starter_project_2025.domain.kanji_study.radical.KanjiRadical;
import com.example.starter_project_2025.domain.kanji_study.radical.KanjiRadicalRepository;
import com.example.starter_project_2025.domain.kanji_study.reading.KanjiReading;
import com.example.starter_project_2025.domain.kanji_study.reading.KanjiReadingRepository;
import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.ObjectMapper;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.boot.CommandLineRunner;
import org.springframework.core.annotation.Order;
import org.springframework.core.io.ClassPathResource;
import org.springframework.stereotype.Component;
import org.springframework.transaction.annotation.Transactional;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * Seeds the self-contained Kanji Study tables (kanji_radicals, kanji_details, kanji_readings,
 * one built-in N5 deck) from {@code resources/seed/kanji-study-seed.json} on startup IF empty.
 *
 * Idempotent (skips when kanji_details already has rows) and resilient: if a restart recreates
 * the schema (e.g. ddl-auto drop), this repopulates automatically — no manual SQL needed.
 * Writes only Kanji-Study tables; never touches the Language `kanjis` table.
 *
 * Data file is regenerated by backend/scripts/gen-kanji-n5-seed.mjs.
 */
@Slf4j
@Component
@Order(50)
@RequiredArgsConstructor
public class KanjiStudyDataSeeder implements CommandLineRunner {

    private final KanjiRadicalRepository radicalRepository;
    private final KanjiDetailRepository detailRepository;
    private final KanjiReadingRepository readingRepository;
    private final KanjiDeckRepository deckRepository;
    private final KanjiDeckItemRepository deckItemRepository;
    private final ObjectMapper objectMapper;

    @Override
    @Transactional
    public void run(String... args) throws Exception {
        if (detailRepository.count() > 0) {
            return; // already seeded
        }

        ClassPathResource resource = new ClassPathResource("seed/kanji-study-seed.json");
        if (!resource.exists()) {
            log.warn("Kanji Study seed file not found (seed/kanji-study-seed.json) — skipping seed.");
            return;
        }

        log.info("Seeding Kanji Study data...");
        JsonNode root = objectMapper.readTree(resource.getInputStream());

        // 1. Radicals (bộ thủ) — keep a number → entity map for linking.
        Map<Integer, KanjiRadical> byNumber = new HashMap<>();
        for (JsonNode r : root.path("radicals")) {
            KanjiRadical radical = radicalRepository.save(KanjiRadical.builder()
                    .number(r.path("number").asInt())
                    .character(text(r, "character"))
                    .hanViet(text(r, "hanViet"))
                    .meaning(text(r, "meaning"))
                    .strokeCount(intOrNull(r, "strokeCount"))
                    .build());
            byNumber.put(radical.getNumber(), radical);
        }

        // 2. Kanji master records + their Hán-Việt readings.
        List<KanjiDetail> ordered = new ArrayList<>();
        for (JsonNode k : root.path("kanji")) {
            Integer radNum = intOrNull(k, "radicalNumber");
            KanjiDetail detail = detailRepository.save(KanjiDetail.builder()
                    .character(text(k, "character"))
                    .onyomi(text(k, "onyomi"))
                    .kunyomi(text(k, "kunyomi"))
                    .meaning(text(k, "meaning"))
                    .jlptLevel(text(k, "jlptLevel"))
                    .strokeCount(intOrNull(k, "strokeCount"))
                    .radical(radNum != null ? byNumber.get(radNum) : null)
                    .build());
            ordered.add(detail);

            int priority = 0;
            for (JsonNode hv : k.path("hanViet")) {
                readingRepository.save(KanjiReading.builder()
                        .kanji(detail)
                        .readingType("HAN_VIET")
                        .value(hv.asText())
                        .priority(priority++)
                        .build());
            }
        }

        // 3. Built-in system deck containing all seeded kanji.
        KanjiDeck deck = deckRepository.save(KanjiDeck.builder()
                .title("JLPT N5 (built-in)")
                .description("79 Hán tự cơ bản trình độ N5.")
                .visibility("PUBLIC")
                .isSystem(true)
                .jlptLevel("N5")
                .totalKanji(ordered.size())
                .build());

        int order = 0;
        for (KanjiDetail detail : ordered) {
            deckItemRepository.save(KanjiDeckItem.builder()
                    .deck(deck)
                    .kanji(detail)
                    .orderIndex(order++)
                    .build());
        }

        log.info("Kanji Study seed complete: {} radicals, {} kanji, deck '{}' with {} items.",
                byNumber.size(), ordered.size(), deck.getTitle(), ordered.size());
    }

    private static String text(JsonNode node, String field) {
        JsonNode v = node.path(field);
        return v.isMissingNode() || v.isNull() ? null : v.asText();
    }

    private static Integer intOrNull(JsonNode node, String field) {
        JsonNode v = node.path(field);
        return v.isMissingNode() || v.isNull() ? null : v.asInt();
    }
}
