import { useEffect, useRef, useState, type ReactNode } from "react";
import { useNavigate, useParams } from "react-router-dom";
import { Loader2, Volume2, AlertTriangle, Info, BookOpen, ChevronRight, ArrowLeftRight } from "lucide-react";

import { MainLayout } from "@/components/layout/MainLayout";
import { Card } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import {
  grammarLearnApi,
  type GrammarDetail,
  type ExampleSentence,
  type RubySegment,
} from "@/api/features/grammar/grammar-learn.api";
import { JpText } from "@/components/grammar/JpText";
import { FuriganaToggle } from "@/components/grammar/FuriganaToggle";
import { useFurigana } from "@/hooks/useFurigana";
import { speakJa, stopJa } from "@/lib/jp-speech";

const STATE_LABEL: Record<string, string> = {
  NEW: "Chưa học",
  LEARNING: "Đang học",
  RELEARNING: "Học lại",
  REVIEW: "Ôn tập",
};

/** Structured "About" JSON generated by the backend (usage bullets + comparisons). */
interface AboutContextItem {
  point: string;
  exampleJp?: string | null;
  exampleVi?: string | null;
}
interface AboutComparison {
  vs: string;
  point: string;
  exampleJp?: string | null;
  exampleVi?: string | null;
}
interface AboutRich {
  context: AboutContextItem[];
  comparisons: AboutComparison[];
}

function parseAbout(raw: string | null): AboutRich | null {
  if (!raw) return null;
  try {
    const o = JSON.parse(raw);
    if (Array.isArray(o?.context) && o.context.length > 0) {
      const context = o.context
        // tolerate the earlier string-array format until the backend regenerates it
        .map((c: unknown) => (typeof c === "string" ? { point: c } : (c as AboutContextItem)))
        .filter((c: AboutContextItem) => c?.point);
      if (context.length === 0) return null;
      return {
        context,
        comparisons: Array.isArray(o.comparisons) ? o.comparisons.filter((c: AboutComparison) => c?.vs) : [],
      };
    }
  } catch {
    /* legacy plain-text cache — rendered as-is below */
  }
  return null;
}

/** 1 → ①, 2 → ② … (falls back to plain number past ⑳) */
function circled(n: number | null): string {
  if (n == null) return "";
  return n >= 1 && n <= 20 ? String.fromCharCode(0x2460 + n - 1) : `(${n})`;
}

function SectionTitle({ icon, children }: { icon?: ReactNode; children: ReactNode }) {
  return (
    <div className="flex items-center gap-2 font-semibold">
      {icon}
      {children}
    </div>
  );
}

function ExampleRow({ jp, vi, note, highlight, segments }: {
  jp: string;
  vi: string | null;
  note?: string | null;
  highlight?: string | null;
  segments?: RubySegment[] | null;
}) {
  return (
    <div className="flex items-start gap-3 rounded-lg bg-muted/50 p-4">
      <Button
        variant="ghost"
        size="icon"
        className="shrink-0 rounded-full text-primary"
        onClick={() => speakJa(jp)}
        aria-label="Đọc câu ví dụ"
      >
        <Volume2 size={18} />
      </Button>
      <div className="flex flex-col gap-1 min-w-0">
        <p className="text-lg leading-loose">
          <JpText text={jp} segments={segments} highlight={highlight ?? null} />
        </p>
        {vi && <p className="text-sm text-muted-foreground">{vi}</p>}
        {note && <p className="text-sm italic text-muted-foreground">{note}</p>}
      </div>
    </div>
  );
}

export default function GrammarDetailPage() {
  const { subUseId } = useParams();
  const navigate = useNavigate();
  const [d, setD] = useState<GrammarDetail | null>(null);
  const [loading, setLoading] = useState(true);
  const topRef = useRef<HTMLDivElement>(null);

  useEffect(() => {
    (async () => {
      setLoading(true);
      try {
        setD(await grammarLearnApi.detail(Number(subUseId)));
      } finally {
        setLoading(false);
      }
    })();
    // Reset scroll on point change so switching ①② siblings doesn't leave the
    // reader stranded mid-page (same route, so the router won't reset it).
    topRef.current?.scrollIntoView({ block: "start" });
  }, [subUseId]);

  // Stop any audio still playing when leaving the page.
  useEffect(() => () => stopJa(), []);

  // Seeded "easy to remember" example + approved reference sentences, deduped.
  const examples: { jp: string; vi: string | null; note?: string | null; highlight?: string | null }[] = [];
  if (d?.exampleJp) {
    examples.push({ jp: d.exampleJp, vi: d.exampleVi, note: d.exampleNote, highlight: d.exampleJpHighlight });
  }
  for (const s of (d?.sentences ?? []) as ExampleSentence[]) {
    if (s.jp && s.jp !== d?.exampleJp) examples.push({ jp: s.jp, vi: s.vi, highlight: s.highlight });
  }

  const title = d?.grammarForm || d?.name || "";
  const hasSiblings = (d?.siblings?.length ?? 0) > 1;
  const about = parseAbout(d?.aboutDetail ?? null);

  // One batched furigana request covering every Japanese string on the page.
  const furi = useFurigana([
    ...examples.map((e) => e.jp),
    ...(about?.context.map((c) => c.exampleJp) ?? []),
    ...(about?.comparisons.map((c) => c.exampleJp) ?? []),
  ]);

  return (
    <MainLayout pathName={{ [`/grammar/detail/${subUseId}`]: "Chi tiết ngữ pháp" }} pageScroll>
      <div ref={topRef} className="w-full max-w-6xl mx-auto flex flex-col gap-5">
        {loading ? (
          <div className="flex justify-center h-40 items-center">
            <Loader2 className="animate-spin text-primary" size={32} />
          </div>
        ) : d ? (
          <>
            {/* ── Header: expression title + badges ── */}
            <div className="flex flex-wrap items-center gap-3">
              <h1 className="text-2xl font-bold">{title}</h1>
              {d.jlptLevel && <Badge variant="secondary">{d.jlptLevel}</Badge>}
              {d.textbookSources.map((src) => (
                <Badge key={src} variant="outline">{src}</Badge>
              ))}
              <div className="ml-auto flex items-center gap-2">
                <FuriganaToggle />
                <Badge>{STATE_LABEL[d.state] ?? d.state}</Badge>
              </div>
            </div>
            {d.titleGloss && (
              <p className="text-muted-foreground -mt-3">{d.titleGloss}</p>
            )}

            {/* ── Usage switcher (① ② …) when the expression has several usages ── */}
            {hasSiblings && (
              <div className="flex flex-wrap gap-2">
                {d.siblings.map((s) => (
                  <Button
                    key={s.subUseId}
                    size="sm"
                    variant={s.subUseId === d.subUseId ? "default" : "outline"}
                    onClick={() => navigate(`/grammar/detail/${s.subUseId}`)}
                  >
                    {circled(s.orderNo)} {s.name}
                  </Button>
                ))}
              </div>
            )}

            {/* ── Structure (only when seeded) ── */}
            {d.structurePattern && (
              <Card className="p-5 gap-3">
                <SectionTitle icon={<Info size={16} className="text-primary" />}>
                  Cấu trúc
                </SectionTitle>
                <p className="text-base">{d.structurePattern}</p>
              </Card>
            )}

            {/* ── About: structured AI write-up (contexts + comparisons) or the short gloss ── */}
            {(about || d.aboutDetail || d.nuanceDescription) && (
              <Card className="p-5 gap-4">
                <SectionTitle icon={<BookOpen size={16} className="text-primary" />}>
                  Về {hasSiblings && d.orderNo != null ? `${title} ${circled(d.orderNo)}` : title}
                </SectionTitle>

                {about ? (
                  <>
                    <ul className="flex flex-col gap-3">
                      {about.context.map((c, i) => (
                        <li key={i} className="flex gap-2 text-sm leading-relaxed">
                          <ChevronRight size={16} className="mt-0.5 shrink-0 text-primary" />
                          <div className="flex flex-col gap-1 min-w-0">
                            <span>{c.point}</span>
                            {c.exampleJp && (
                              <button
                                type="button"
                                onClick={() => speakJa(c.exampleJp!)}
                                className="self-start text-left text-muted-foreground hover:text-foreground transition-colors"
                                title="Bấm để nghe"
                              >
                                <span className="text-foreground/90 leading-loose">
                                  <JpText text={c.exampleJp} segments={furi[c.exampleJp]} />
                                </span>
                                {c.exampleVi && <span className="text-xs"> — {c.exampleVi}</span>}
                              </button>
                            )}
                          </div>
                        </li>
                      ))}
                    </ul>

                    {about.comparisons.length > 0 && (
                      <div className="flex flex-col gap-3 pt-1">
                        <div className="flex items-center gap-2 text-sm font-semibold text-muted-foreground">
                          <ArrowLeftRight size={14} />
                          So sánh với mẫu gần nghĩa
                        </div>
                        <div className="grid gap-3 lg:grid-cols-2">
                          {about.comparisons.map((c, i) => (
                            <div key={i} className="rounded-lg border border-border p-4 flex flex-col gap-2">
                              <span className="font-semibold text-primary">{c.vs}</span>
                              <p className="text-sm leading-relaxed">{c.point}</p>
                              {c.exampleJp && (
                                <div className="mt-auto flex items-start gap-2 rounded-md bg-muted/50 p-3">
                                  <Button
                                    variant="ghost"
                                    size="icon"
                                    className="size-7 shrink-0 rounded-full text-primary"
                                    onClick={() => speakJa(c.exampleJp!)}
                                    aria-label="Đọc câu ví dụ"
                                  >
                                    <Volume2 size={14} />
                                  </Button>
                                  <div className="min-w-0">
                                    <p className="text-base leading-loose">
                                      <JpText text={c.exampleJp} segments={furi[c.exampleJp]} />
                                    </p>
                                    {c.exampleVi && (
                                      <p className="text-xs text-muted-foreground">{c.exampleVi}</p>
                                    )}
                                  </div>
                                </div>
                              )}
                            </div>
                          ))}
                        </div>
                      </div>
                    )}
                  </>
                ) : (
                  <p className="text-sm leading-relaxed whitespace-pre-line">
                    {d.aboutDetail || d.nuanceDescription}
                  </p>
                )}
              </Card>
            )}

            {/* ── Examples ── */}
            {examples.length > 0 && (
              <Card className="p-5 gap-3">
                <SectionTitle>Ví dụ</SectionTitle>
                <div className="flex flex-col gap-3">
                  {examples.map((ex, i) => (
                    <ExampleRow
                      key={i}
                      jp={ex.jp}
                      vi={ex.vi}
                      note={ex.note}
                      highlight={ex.highlight}
                      segments={furi[ex.jp]}
                    />
                  ))}
                </div>
              </Card>
            )}

            {/* ── Common mistakes ── */}
            {d.commonMistakes.length > 0 && (
              <Card className="p-5 gap-3 border-amber-500/30">
                <SectionTitle icon={<AlertTriangle size={16} className="text-amber-500" />}>
                  Lỗi thường gặp
                </SectionTitle>
                <div className="flex flex-col gap-2">
                  {d.commonMistakes.map((m, i) => (
                    <div key={i} className="text-sm">
                      {m.pattern && <span className="font-medium text-amber-600 dark:text-amber-400">{m.pattern}</span>}
                      {m.pattern && m.hint && <span className="text-muted-foreground"> — </span>}
                      {m.hint && <span className="text-muted-foreground">{m.hint}</span>}
                    </div>
                  ))}
                </div>
              </Card>
            )}

            {/* ── Notes ("Chú ý") of the whole expression ── */}
            {d.grammarNotes && (
              <Card className="p-5 gap-3 bg-muted/40">
                <SectionTitle>Chú ý</SectionTitle>
                <p className="text-sm leading-relaxed whitespace-pre-line">{d.grammarNotes}</p>
              </Card>
            )}

            <Button
              className="self-start"
              onClick={() => navigate(d.jlptLevel ? `/grammar/learn?level=${d.jlptLevel}` : "/grammar/learn")}
            >
              Bắt đầu ôn
            </Button>
          </>
        ) : (
          <Card className="p-6 text-sm text-muted-foreground">Không tìm thấy.</Card>
        )}
      </div>
    </MainLayout>
  );
}
