import type { LucideIcon } from "lucide-react"

import {
    Activity,
    AlertTriangle,
    BarChart3,
    Bell,
    BookOpen,
    Bookmark,
    Briefcase,
    Bug,
    Building,
    Calendar,
    CalendarDays,
    Camera,
    Check,
    ClipboardCheck,
    Cloud,
    CloudDownload,
    CloudUpload,
    Code,
    Cpu,
    CreditCard,
    Database,
    DollarSign,
    Download,
    ExternalLink,
    Eye,
    EyeOff,
    File,
    FileText,
    Filter,
    Folder,
    FolderOpen,
    Globe,
    GraduationCap,
    HardDrive,
    HelpCircle,
    Home,
    Image,
    Info,
    Key,
    KeyRound,
    Keyboard,
    Laptop,
    Layers,
    Link,
    List,
    Lock,
    Mail,
    MapPin,
    MessageCircle,
    Mic,
    Minus,
    Monitor,
    Music,
    Package,
    Pause,
    Pencil,
    Phone,
    PieChart,
    Play,
    Plus,
    RefreshCw,
    Rocket,
    Save,
    Search,
    Server,
    Settings,
    Shield,
    ShieldAlert,
    ShieldCheck,
    ShoppingCart,
    Smartphone,
    Star,
    Tag,
    Tags,
    Terminal,
    Trash2,
    TrendingDown,
    TrendingUp,
    Unlock,
    Upload,
    User,
    UserMinus,
    UserPlus,
    Users,
    Video,
    Wallet,
    X,
    LayoutDashboard,
} from "lucide-react"

export const iconMap = {
    // Navigation
    home: Home,
    dashboard: LayoutDashboard,
    menu: List,
    menus: List,
    layers: Layers,
    menu_groups: Layers,
    "menu-groups": Layers,
    folder: Folder,
    "folder-open": FolderOpen,
    file: File,
    "file-text": FileText,
    search: Search,
    filter: Filter,
    "map-pin": MapPin,

    // User / Auth / Security
    users: Users,
    user: User,
    person: User,
    people: Users,
    "user-plus": UserPlus,
    "user-minus": UserMinus,
    roles: Shield,
    role: Shield,
    permissions: KeyRound,
    permission: KeyRound,
    security: Shield,
    "shield-check": ShieldCheck,
    "shield-alert": ShieldAlert,
    key: Key,
    "key-round": KeyRound,
    lock: Lock,
    unlock: Unlock,

    // Common actions
    plus: Plus,
    minus: Minus,
    check: Check,
    x: X,
    close: X,
    edit: Pencil,
    pencil: Pencil,
    delete: Trash2,
    trash: Trash2,
    save: Save,
    download: Download,
    upload: Upload,
    refresh: RefreshCw,
    eye: Eye,
    "eye-off": EyeOff,

    // Communication / Link
    bell: Bell,
    mail: Mail,
    message: MessageCircle,
    phone: Phone,
    globe: Globe,
    link: Link,
    "external-link": ExternalLink,

    // Time / Info
    calendar: Calendar,
    "calendar-days": CalendarDays,
    info: Info,
    help: HelpCircle,
    "alert-triangle": AlertTriangle,

    // Business / Commerce
    building: Building,
    briefcase: Briefcase,
    books: BookOpen,
    book: BookOpen,
    "book-open": BookOpen,
    "clipboard-check": ClipboardCheck,
    bookmark: Bookmark,
    tag: Tag,
    tags: Tags,
    star: Star,
    "shopping-cart": ShoppingCart,
    "credit-card": CreditCard,
    "dollar-sign": DollarSign,
    wallet: Wallet,
    package: Package,
    "graduation-cap": GraduationCap,

    // Data / Infra
    database: Database,
    server: Server,
    "hard-drive": HardDrive,
    cloud: Cloud,
    "cloud-upload": CloudUpload,
    "cloud-download": CloudDownload,
    "bar-chart": BarChart3,
    "pie-chart": PieChart,
    activity: Activity,
    "trending-up": TrendingUp,
    "trending-down": TrendingDown,

    // Device / Media
    monitor: Monitor,
    laptop: Laptop,
    smartphone: Smartphone,
    image: Image,
    camera: Camera,
    video: Video,
    play: Play,
    pause: Pause,
    keyboard: Keyboard,
    music: Music,
    mic: Mic,

    // Tech / Dev
    settings: Settings,
    code: Code,
    terminal: Terminal,
    bug: Bug,
    rocket: Rocket,
    cpu: Cpu,
} satisfies Record<string, LucideIcon>

export type IconKey = keyof typeof iconMap

const toTitle = (key: string) =>
    key
        .replace(/[_-]+/g, " ")
        .replace(/\b\w/g, (c) => c.toUpperCase())

export const iconKeyOptions: Array<{ label: string; value: IconKey }> = Object
    .keys(iconMap)
    .map((key) => ({
        value: key as IconKey,
        label: `${toTitle(key)} (${key})`,
    }))
    .sort((a, b) => a.value.localeCompare(b.value))
