package com.example.starter_project_2025.domain.production.seed;

import com.example.starter_project_2025.domain.production.grammar.GrammarMarker;
import com.example.starter_project_2025.domain.production.grammar.GrammarMarkerRepository;
import com.example.starter_project_2025.domain.production.grammar.GrammarSpotterService;
import com.example.starter_project_2025.domain.production.grammar.GrammarSubUse;
import com.example.starter_project_2025.domain.production.grammar.GrammarSubUseRepository;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.boot.CommandLineRunner;
import org.springframework.core.annotation.Order;
import org.springframework.stereotype.Component;

import java.util.List;

/**
 * Bulk N3 dictionary for the translate-page "Grammar Spotter"
 * ({@link GrammarSpotterService}). Sourced from the N3 grammar index of
 * tiengnhatdongian.com and curated by hand into this codebase's two-track model.
 *
 * <h2>Relationship to {@link GrammarDictionarySeeder}</h2>
 * {@code GrammarDictionarySeeder} (@Order 101) owns the small, canonical
 * cross-level set that is kept disjoint from the production drill. <b>This</b>
 * seeder (@Order 102) is purely additive coverage for the Spotter: ~130 extra
 * N3 patterns so real Japanese sentences light up more reliably. The two sets do
 * not share {@code detectorKey}s, and every insert is guarded by
 * {@link GrammarSubUseRepository#existsByDetectorKey} so re-runs are no-ops.
 *
 * <h2>Track A vs Track B (the "hybrid" design)</h2>
 * <ul>
 *   <li><b>Track A — plain keyword</b> ({@code regex == null}): for invariant
 *       expressions (によって, について, につれて…). The Spotter strips the leading
 *       {@code ～} and feeds the rest to Aho-Corasick. No AI involved.</li>
 *   <li><b>Track B — hand-written regex</b> ({@code regex != null}): for
 *       conjugating endings and <i>split</i> patterns that have words in the
 *       middle (決して～ない, ば～ほど, いくら～ても…). A plain keyword would never
 *       match these because the surface text has tokens between the two halves;
 *       {@code .{0,N}} bridges that gap. Regexes are run against the
 *       separator-free surface join, so they match both kanji and kana spellings
 *       where it matters.</li>
 * </ul>
 *
 * <p>High-frequency bare particles (こと, もの, など, まで, ほど, だけ, ても…) are
 * deliberately excluded: as plain keywords they fire on almost every sentence and
 * drown out the useful hits.
 *
 * <p>No LLM at runtime, and none at seed-time either — every regex here is
 * authored by hand.
 */
@Slf4j
@Component
@Order(102)
@RequiredArgsConstructor
public class GrammarSpotterN3Seeder implements CommandLineRunner {

    private final GrammarSubUseRepository subUseRepository;
    private final GrammarMarkerRepository markerRepository;
    private final GrammarSpotterService grammarSpotter;

    /** key, display pattern, JLPT level, Vietnamese nuance, detection regex (null ⇒ Track A keyword). */
    private record Entry(String key, String pattern, String level, String nuance, String regex) {}

    private static final String N3 = "N3";

    private static final List<Entry> DICTIONARY = List.of(
            // ── Track A: invariant keywords (regex = null) ───────────────────────
            new Entry("spot_n3_aida_during", "～あいだ", N3,
                    "Trong lúc, trong khi (khoảng thời gian).", null),
            new Entry("spot_n3_tekaradenaito", "～てからでないと", N3,
                    "Nếu chưa… thì chưa thể…", null),
            new Entry("spot_n3_tabini", "～たびに", N3,
                    "Cứ mỗi lần… thì…", null),
            new Entry("spot_n3_tsuideni", "～ついでに", N3,
                    "Nhân tiện…/ Tiện thể…", null),
            new Entry("spot_n3_kurainara", "～くらいなら", N3,
                    "Nếu phải… thì thà…", null),
            new Entry("spot_n3_hanmen", "～反面", N3,
                    "Nhưng mặt khác thì…", null),
            new Entry("spot_n3_ippou", "～一方", N3,
                    "Mặt khác lại…/ Vừa… vừa…", null),
            new Entry("spot_n3_toiuyori", "～というより", N3,
                    "Đúng hơn là…", null),
            new Entry("spot_n3_kotokara", "～ことから", N3,
                    "Do…/ Vì…/ Bởi…", null),
            new Entry("spot_n3_nitsuite", "～について", N3,
                    "Về…/ Liên quan đến…", null),
            new Entry("spot_n3_toshite", "～として", N3,
                    "Với tư cách là…", null),
            new Entry("spot_n3_toshitara", "～としたら", N3,
                    "Giả sử… thì…", null),
            new Entry("spot_n3_toiunoha", "～というのは", N3,
                    "Cái gọi là…", null),
            new Entry("spot_n3_bakaridenaku", "～ばかりでなく", N3,
                    "Không chỉ… mà còn…", null),
            new Entry("spot_n3_kuseni", "～くせに", N3,
                    "Vậy mà…/ Thế mà…", null),
            new Entry("spot_n3_karaniha", "～からには", N3,
                    "Một khi đã… thì sẽ…", null),
            new Entry("spot_n3_wohajime", "～をはじめ", N3,
                    "Tiêu biểu như là…", null),
            new Entry("spot_n3_nitsurete", "～につれて", N3,
                    "Càng… càng…", null),
            new Entry("spot_n3_hamotoyori", "～はもとより", N3,
                    "… thì là đương nhiên…", null),
            new Entry("spot_n3_monodakara", "～ものだから", N3,
                    "Vì…/ Tại vì…", null),
            new Entry("spot_n3_karatoitte", "～からといって", N3,
                    "Cho dù có nói là… thì…", null),
            new Entry("spot_n3_wokikkakeni", "～をきっかけに", N3,
                    "Nhân… mà…/ Lấy… làm cơ hội.", null),
            new Entry("spot_n3_nishiteha", "～にしては", N3,
                    "Tuy… nhưng…", null),
            new Entry("spot_n3_ppanashi", "～っぱなし", N3,
                    "Cứ nguyên… như thế.", null),
            new Entry("spot_n3_nazenara", "～なぜなら", N3,
                    "Lý do là vì…", null),
            new Entry("spot_n3_sonotame", "～そのため", N3,
                    "Vì lý do đó…", null),
            new Entry("spot_n3_ichihoude", "～一方で", N3,
                    "Mặt khác…/ Ngày càng…", null),
            new Entry("spot_n3_toshitemo", "～としても", N3,
                    "Cho dù…", null),
            new Entry("spot_n3_tokoroga", "～ところが", N3,
                    "Nhưng mà…", null),
            new Entry("spot_n3_tokorode", "～ところで", N3,
                    "Nhân tiện…", null),
            new Entry("spot_n3_moshikashitara", "～もしかしたら", N3,
                    "Có lẽ là…", null),
            new Entry("spot_n3_hamochiron", "～はもちろん", N3,
                    "… thì đương nhiên rồi…", null),
            new Entry("spot_n3_soretomo", "～それとも", N3,
                    "Hoặc…/ Hoặc là…", null),
            new Entry("spot_n3_sonokekka", "～その結果", N3,
                    "Kết quả là…", null),
            new Entry("spot_n3_tsumari", "～つまり", N3,
                    "Hay nói cách khác…", null),
            new Entry("spot_n3_douse", "～どうせ", N3,
                    "Đằng nào thì…", null),
            new Entry("spot_n3_naraba", "～ならば", N3,
                    "Nếu… thì…", null),
            new Entry("spot_n3_niseyo", "～にせよ", N3,
                    "Cho dù…", null),
            new Entry("spot_n3_toiumonoda", "～というものだ", N3,
                    "Là…/ Chính là…", null),
            new Entry("spot_n3_toiuto", "～というと", N3,
                    "Nói đến… thì…", null),
            new Entry("spot_n3_toittemo", "～といっても", N3,
                    "Cho dù nói là…", null),
            new Entry("spot_n3_toieba", "～といえば", N3,
                    "Nói đến… thì…", null),
            new Entry("spot_n3_bakarika", "～ばかりか", N3,
                    "Không chỉ… mà còn…", null),
            new Entry("spot_n3_toiumonoha", "～というものは", N3,
                    "Cái gọi là…", null),
            new Entry("spot_n3_nishitemo", "～にしても", N3,
                    "Cho dù…", null),
            new Entry("spot_n3_toshiteha", "～としては", N3,
                    "Với… thì…", null),
            new Entry("spot_n3_dakedenaku", "～だけでなく", N3,
                    "Không chỉ… mà còn…", null),
            new Entry("spot_n3_seizei", "～せいぜい", N3,
                    "Tối đa, hết mức…", null),
            new Entry("spot_n3_nakanaka", "～なかなか", N3,
                    "Khá là…/ Quả là…", null),
            new Entry("spot_n3_mushiro", "～むしろ", N3,
                    "Ngược lại – Trái lại.", null),
            new Entry("spot_n3_yoreba", "～によれば", N3,
                    "Theo…", null),
            new Entry("spot_n3_karakoso", "～からこそ", N3,
                    "Chính vì…", null),
            new Entry("spot_n3_darake", "～だらけ", N3,
                    "Toàn là…", null),
            new Entry("spot_n3_ppoi", "～っぽい", N3,
                    "Như…/ Cứ như là…", null),
            new Entry("spot_n3_zurai", "～づらい", N3,
                    "Khó (làm gì)…", null),
            new Entry("spot_n3_nante", "～なんて", N3,
                    "Cái thứ như…/ Nào ngờ…", null),
            new Entry("spot_n3_tekonokata", "～てこのかた", N3,
                    "Sau khi… thì… suốt.", null),
            new Entry("spot_n3_sonokuse", "～そのくせ", N3,
                    "Dù vậy, vậy mà…", null),

            // ── Track B: conjugating / split patterns (hand-written regex) ───────
            new Entry("spot_n3_tokoroda", "～ところだ", N3,
                    "Sắp…/ Đang…/ Vừa mới…",
                    "ところ(だ|です|でし|だっ)"),
            new Entry("spot_n3_tokoroni", "～ところに", N3,
                    "Đúng lúc…/ Trong lúc… thì…",
                    "ところ(に|へ|を)"),
            new Entry("spot_n3_toori", "～とおり", N3,
                    "Đúng như…/ Theo đúng…",
                    "とおり|どおり|通り"),
            new Entry("spot_n3_ba_hodo", "～ば～ほど", N3,
                    "Càng… càng…",
                    "ば.{0,8}ほど"),
            new Entry("spot_n3_hodo_wanai", "～ほど～はない", N3,
                    "Không có … nào bằng…",
                    "ほど.{0,12}はない"),
            new Entry("spot_n3_nikagiru", "～に限る", N3,
                    "… là nhất /… là tốt nhất.",
                    "に限る|にかぎる"),
            new Entry("spot_n3_nitaishite", "～に対して", N3,
                    "Đối với…/ Ngược lại…",
                    "に対して|に対し|にたいして"),
            new Entry("spot_n3_kawarini", "～かわりに", N3,
                    "Thay vì…/ Thay cho…",
                    "かわりに|代わりに|変わりに"),
            new Entry("spot_n3_nodakara", "～のだから", N3,
                    "Vì, do… nên…",
                    "のだから|んだから"),
            new Entry("spot_n3_sae_ba", "～さえ～ば", N3,
                    "Chỉ cần… thì…",
                    "さえ.{0,8}ば"),
            new Entry("spot_n3_tatoe_temo", "たとえ～ても", N3,
                    "Cho dù… đi nữa thì cũng…",
                    "たとえ.{0,10}ても"),
            new Entry("spot_n3_toiukotoda", "～ということだ", N3,
                    "Có nghĩa là…/ Tóm lại là…",
                    "ということ(だ|です)"),
            new Entry("spot_n3_tonokotoda", "～とのことだ", N3,
                    "Nghe nói là…",
                    "とのこと(だ|です)"),
            new Entry("spot_n3_toiwareteiru", "～と言われている", N3,
                    "Người ta nói rằng…",
                    "と言われている|といわれている"),
            new Entry("spot_n3_hazuganai", "～はずがない", N3,
                    "Làm gì có chuyện…",
                    "はずがない|はずが無い|はずはない"),
            new Entry("spot_n3_wakeganai", "～わけがない", N3,
                    "Không thể nào mà…",
                    "わけがない|わけが無い|訳がない"),
            new Entry("spot_n3_towakagiranai", "～とは限らない", N3,
                    "Không hẳn là…",
                    "とは限らない|とはかぎらない"),
            new Entry("spot_n3_wakedewanai", "～わけではない", N3,
                    "Không hẳn là…",
                    "わけではない|わけでは無い|訳ではない"),
            new Entry("spot_n3_naikotowanai", "～ないことはない", N3,
                    "Không phải là không…",
                    "ないことはない|無いことはない"),
            new Entry("spot_n3_moraitai", "～もらいたい", N3,
                    "Tôi muốn bạn (làm)…",
                    "もらいたい|いただきたい|頂きたい"),
            new Entry("spot_n3_tehoshii", "～てほしい", N3,
                    "Muốn ai đó làm gì…",
                    "てほしい|て欲しい|でほしい"),
            new Entry("spot_n3_toii", "～といい", N3,
                    "Ước gì…/ Phải chi…",
                    "といい(ね|な|よ|です|の)"),
            new Entry("spot_n3_taradoudesuka", "～たらどうですか", N3,
                    "Sao không…?",
                    "たらどう"),
            new Entry("spot_n3_kotonishiteiru", "～ことにしている", N3,
                    "Luôn cố gắng…/ Có thói quen…",
                    "ことにしている|ことにしてる"),
            new Entry("spot_n3_younisuru", "～ようにする", N3,
                    "Cố gắng (làm)…",
                    "ようにする|ようにします|ようにして"),
            new Entry("spot_n3_kanoyouda", "～かのようだ", N3,
                    "Cứ như thể là…",
                    "かのよう(だ|です|に|な)"),
            new Entry("spot_n3_wakeda", "～わけだ", N3,
                    "Thảo nào, hèn chi…",
                    "わけだ|わけです|訳だ"),
            new Entry("spot_n3_wakeniwaikanai", "～わけにはいかない", N3,
                    "Không thể…",
                    "わけにはいかない|わけにはいけない|訳にはいかない"),
            new Entry("spot_n3_kotoninaru", "～ことになる", N3,
                    "Bị/ được/ quy định…",
                    "ことになる|ことになっ|ことになり"),
            new Entry("spot_n3_youninatteiru", "～ようになっている", N3,
                    "Chức năng/ cơ chế của…",
                    "ようになっている|ようになってる"),
            new Entry("spot_n3_gachi", "～がち", N3,
                    "Thường hay…/ Dễ…",
                    "がち(だ|な|に|の|です)"),
            new Entry("spot_n3_youdesu", "～ようです", N3,
                    "Hình như…",
                    "ようです|ようだった|ようでした"),
            new Entry("spot_n3_totan", "～たとたん", N3,
                    "Vừa mới… thì…",
                    "たとたん|た途端"),
            new Entry("spot_n3_saichuu", "～最中", N3,
                    "Đang lúc…",
                    "最中|さいちゅう"),
            new Entry("spot_n3_takke", "～たっけ", N3,
                    "Hình như là… nhỉ?",
                    "たっけ|だっけ"),
            new Entry("spot_n3_nikurabete", "～に比べて", N3,
                    "So với…",
                    "に比べて|にくらべて|に比べ"),
            new Entry("spot_n3_tatokoro", "～たところ", N3,
                    "Sau khi làm… thì…",
                    "たところ(、|。|だ|です|が)"),
            new Entry("spot_n3_tokorodatta", "～ところだった", N3,
                    "Suýt nữa thì…",
                    "ところだった|ところでした"),
            new Entry("spot_n3_nioite", "～において", N3,
                    "Tại…/ Trong…",
                    "において|における|に於いて"),
            new Entry("spot_n3_shikanai", "～しかない", N3,
                    "Đành phải…",
                    "しかない|しか無い"),
            new Entry("spot_n3_kotowanai", "～ことはない", N3,
                    "Không cần thiết phải…",
                    "ことはない|ことは無い"),
            new Entry("spot_n3_nikawatte", "～にかわって", N3,
                    "Thay thế cho…",
                    "にかわって|に代わって|に変わって"),
            new Entry("spot_n3_warini", "～わりに", N3,
                    "Tuy… nhưng…",
                    "わりに|わりには|割に"),
            new Entry("spot_n3_kara_nikakete", "～から～にかけて", N3,
                    "Từ… đến…",
                    "から.{0,12}にかけて"),
            new Entry("spot_n3_nikanshite", "～に関して", N3,
                    "Liên quan đến…",
                    "に関して|にかんして|に関する"),
            new Entry("spot_n3_kireru", "～切れる", N3,
                    "Có thể hoàn thành…",
                    "切れる|きれる"),
            new Entry("spot_n3_hajimeru", "～始める", N3,
                    "Bắt đầu…",
                    "始める|始めた|はじめる|はじめた"),
            new Entry("spot_n3_teiku", "～ていく", N3,
                    "Tiếp tục (làm gì)…",
                    "ていく|ていきま|ていっ"),
            new Entry("spot_n3_njanai", "～んじゃない", N3,
                    "Không phải là … hay sao?",
                    "んじゃない|んじゃ無い"),
            new Entry("spot_n3_niwatatte", "～にわたって", N3,
                    "Suốt…/ Khắp…",
                    "にわたって|に渡って|にわたり|にわたる"),
            new Entry("spot_n3_gimi", "～ぎみ", N3,
                    "Có vẻ hơi…",
                    "ぎみ|気味"),
            new Entry("spot_n3_nihanshite", "～に反して", N3,
                    "Trái với… thì…",
                    "に反して|にはんして|に反する"),
            new Entry("spot_n3_saiwa", "～際は", N3,
                    "Khi…/ Lúc…",
                    "際(は|に|の)|さいは|さいに"),
            new Entry("spot_n3_nikuwaete", "～に加えて", N3,
                    "Không chỉ… mà còn…",
                    "に加えて|にくわえて|に加え"),
            new Entry("spot_n3_chuushinni", "～を中心に", N3,
                    "Chủ yếu là…/ Lấy… làm trung tâm.",
                    "中心に|ちゅうしんに|を中心"),
            new Entry("spot_n3_muke", "～向け", N3,
                    "Dành cho…",
                    "向け(の|に|だ|です|られ)"),
            new Entry("spot_n3_nitomonatte", "～に伴って", N3,
                    "Cùng với…",
                    "に伴って|にともなって|に伴い|に伴う"),
            new Entry("spot_n3_nikimatteiru", "～に決まっている", N3,
                    "Chắc chắn là…",
                    "に決まっている|にきまっている|に決まってる"),
            new Entry("spot_n3_wotsuujite", "～を通じて", N3,
                    "Thông qua…",
                    "を通じて|をつうじて|を通して"),
            new Entry("spot_n3_muki", "～向き", N3,
                    "Phù hợp với…",
                    "向き(の|に|だ|です)"),
            new Entry("spot_n3_nishitagatte", "～にしたがって", N3,
                    "Càng… càng…/ Tùy theo…",
                    "にしたがって|に従って|に従い"),
            new Entry("spot_n3_totomoni", "～と共に", N3,
                    "Cùng với…",
                    "と共に|とともに"),
            new Entry("spot_n3_youganai", "～ようがない", N3,
                    "Không có cách nào…",
                    "ようがない|ようが無い|しようがない"),
            new Entry("spot_n3_teirai", "～て以来", N3,
                    "Kể từ khi… thì… suốt.",
                    "て以来|ていらい"),
            new Entry("spot_n3_hokanai", "～ほかない", N3,
                    "Chỉ còn cách…",
                    "ほかない|ほか無い|他ない"),
            new Entry("spot_n3_womotoni", "～をもとに", N3,
                    "Dựa trên…",
                    "をもとに|を基に|を元に"),
            new Entry("spot_n3_nimotozuite", "～に基づいて", N3,
                    "Dựa trên…",
                    "に基づいて|にもとづいて|に基づき|に基づく"),
            new Entry("spot_n3_monoka", "～ものか", N3,
                    "Không đời nào…",
                    "ものか|もんか"),
            new Entry("spot_n3_hazudatta", "～はずだった", N3,
                    "Lẽ ra thì…",
                    "はずだった|はずでした"),
            new Entry("spot_n3_tamaranai", "～たまらない", N3,
                    "Không chịu nổi…",
                    "てたまらない|でたまらない|堪らない"),
            new Entry("spot_n3_tenaranai", "～てならない", N3,
                    "Không chịu nổi…",
                    "てならない|でならない|て成らない"),
            new Entry("spot_n3_wokomete", "～をこめて", N3,
                    "Với tất cả (tấm lòng)…",
                    "をこめて|を込めて"),
            new Entry("spot_n3_osoregaaru", "～おそれがある", N3,
                    "E là…/ E rằng…",
                    "おそれがある|恐れがある|おそれが"),
            new Entry("spot_n3_temiseru", "～てみせる", N3,
                    "Làm… cho xem.",
                    "てみせる|て見せる"),
            new Entry("spot_n3_ikura_temo", "いくら～ても", N3,
                    "Dù có… bao nhiêu đi nữa.",
                    "いくら.{0,10}ても"),
            new Entry("spot_n3_mama", "～まま", N3,
                    "Vẫn – cứ để nguyên.",
                    "まま(だ|です|でした|だった|に|で)"),
            new Entry("spot_n3_furiwosuru", "～ふりをする", N3,
                    "Giả vờ…/ Tỏ vẻ…",
                    "ふりをする|振りをする|ふりをし"),
            new Entry("spot_n3_ndatte", "～んだって", N3,
                    "Nghe nói là…",
                    "んだって|んですって"),
            new Entry("spot_n3_bayokatta", "～ばよかった", N3,
                    "Phải chi…",
                    "ばよかった|ば良かった"),
            new Entry("spot_n3_sonoue", "～その上", N3,
                    "Thêm vào đó…",
                    "その上|そのうえ"),
            new Entry("spot_n3_moshi_nara", "もし～なら", N3,
                    "Nếu như… thì…",
                    "もし.{0,12}なら"),
            new Entry("spot_n3_kesshite_nai", "決して～ない", N3,
                    "Nhất quyết không…",
                    "決して.{0,12}な(い|かった|く)|けっして.{0,12}な(い|かった)"),
            new Entry("spot_n3_mettani_nai", "めったに～ない", N3,
                    "Hiếm khi…",
                    "めったに.{0,12}な(い|かった)|滅多に.{0,12}な(い|かった)"),
            new Entry("spot_n3_sukoshimo_nai", "少しも～ない", N3,
                    "Một chút cũng không…",
                    "少しも.{0,12}な(い|かった)|すこしも.{0,12}な(い|かった)"),
            new Entry("spot_n3_mattaku_nai", "全く～ない", N3,
                    "Hoàn toàn không…",
                    "全く.{0,12}な(い|かった)|まったく.{0,12}な(い|かった)"),
            new Entry("spot_n3_moshi_toshitemo", "もし～としても", N3,
                    "Ngay cả nếu…",
                    "もし.{0,12}としても"),
            new Entry("spot_n3_marude_you", "まるで～よう", N3,
                    "Cứ như thể là…",
                    "まるで.{0,12}よう"),
            new Entry("spot_n3_tagaru", "～たがる", N3,
                    "Muốn…/ Thích…",
                    "たがる|たがった|たがって|たがり"),
            new Entry("spot_n3_monoda", "～ものだ", N3,
                    "Thường hay…",
                    "ものだ|ものです|もんだ"),
            new Entry("spot_n3_donnani_kotoka", "どんなに～ことか", N3,
                    "Thật là, cực kỳ…",
                    "どんなに.{0,15}ことか"),
            new Entry("spot_n3_donnani_temo", "どんなに～ても", N3,
                    "Dẫu cho… cũng…",
                    "どんなに.{0,12}ても"),
            new Entry("spot_n3_youniiwareru", "～ように言われる", N3,
                    "Được/ bị nói là (hãy)…",
                    "ように言われ|ようにいわれ"),
            new Entry("spot_n3_tegoran", "～てごらん", N3,
                    "Thử (làm gì)…",
                    "てごらん|て御覧"),
            new Entry("spot_n3_dakeshika_nai", "～だけしか～ない", N3,
                    "Chỉ… mà thôi.",
                    "だけしか.{0,10}な(い|かった)"),
            new Entry("spot_n3_youtoomou", "～ようと思います", N3,
                    "Sẽ…/ Định sẽ…",
                    "ようと思|ようとおも"),
            new Entry("spot_n3_teoku", "～ておく", N3,
                    "Sẵn – trước.",
                    "ておく|ておきま|ておい"),
            new Entry("spot_n3_tsumoridatta", "～つもりだった", N3,
                    "Đã định làm…",
                    "つもりだった|つもりでした"),
            new Entry("spot_n3_tehajimete", "～てはじめて", N3,
                    "Kể từ khi… mới…",
                    "てはじめて|て初めて"),
            new Entry("spot_n3_sasetekudasai", "～させてください", N3,
                    "Xin cho tôi…",
                    "させてください|させて下さい"),
            new Entry("spot_n3_atowa_dake", "～あとは～だけ", N3,
                    "Chỉ còn… nữa (là xong).",
                    "あとは.{0,10}だけ"),
            new Entry("spot_n3_dakedeii", "～だけでいい", N3,
                    "Chỉ cần… là được.",
                    "だけでいい|だけで良い|だけでよい"),
            new Entry("spot_n3_temoraenai", "～てもらえない", N3,
                    "Làm… cho tôi được không?",
                    "てもらえない|て貰えない|てもらえません"),
            new Entry("spot_n3_temo_temo", "～ても～ても", N3,
                    "Dù có… bao nhiêu lần.",
                    "ても.{0,8}ても"),
            new Entry("spot_n3_teshouganai", "～てしょうがない", N3,
                    "Không thể chịu nổi.",
                    "てしょうがない|てしようがない"),
            new Entry("spot_n3_totemo_nai", "～とても～ない", N3,
                    "Không thể nào mà…",
                    "とても.{0,12}な(い|かった)"),
            new Entry("spot_n3_ninareru", "～に慣れる", N3,
                    "Quen với…",
                    "に慣れる|になれる|に慣れ"),
            new Entry("spot_n3_doushitemo_nai", "どうしても～ない", N3,
                    "Không cách nào… được.",
                    "どうしても.{0,12}な(い|かった)"),
            new Entry("spot_n3_teshikataganai", "～てしかたがない", N3,
                    "Không thể chịu nổi…",
                    "てしかたがない|て仕方がない|てしかたが"),
            new Entry("spot_n3_kotogaaru", "～ことがある", N3,
                    "Có lúc…/ Có khi…",
                    "ことがある|ことが有る"),
            new Entry("spot_n3_nado_nai", "～など～ない", N3,
                    "… không … chút nào.",
                    "など.{0,10}な(い|かった)"),
            new Entry("spot_n3_tarinankashite", "～たりなんかして", N3,
                    "Chẳng hạn (làm)…",
                    "たりなんかして|たりなんか"),
            new Entry("spot_n3_baiitoomou", "～ばいいと思う", N3,
                    "Hy vọng…",
                    "ばいいと思|ば良いと思|ばいいとおも"),
            new Entry("spot_n3_nanka_nai", "～なんか～ない", N3,
                    "Không … đâu.",
                    "なんか.{0,10}な(い|かった)"),
            new Entry("spot_n3_nado_monoka", "～など～ものか", N3,
                    "Không thể nào…",
                    "など.{0,10}ものか"),
            new Entry("spot_n3_kotoka", "～ことか", N3,
                    "Thật là… biết mấy.",
                    "ことか(。|！|\\?|、|，)"),
            new Entry("spot_n3_youniiu", "～ように言う", N3,
                    "Hãy bảo (ai làm gì)…",
                    "ように言う|ようにいう|ように言っ"),
            new Entry("spot_n3_izen", "～以前", N3,
                    "Trước đây…/ Trước khi…",
                    "以前(は|に|の|だ)"),
            new Entry("spot_n3_daroutoomou", "～だろうと思う", N3,
                    "Tôi nghĩ có lẽ…",
                    "だろうと思|だろうとおも"),
            new Entry("spot_n3_nimukete", "～に向けて", N3,
                    "Hướng đến…",
                    "に向けて|にむけて|に向け"),
            new Entry("spot_n3_yara_yara", "～やら～やら", N3,
                    "Vừa… vừa…",
                    "やら.{0,10}やら"),
            new Entry("spot_n3_tokanantoka", "～とかなんとか", N3,
                    "Là… hay gì đó…",
                    "とかなんとか|とか何とか"),
            new Entry("spot_n3_younimieru", "～ように見える", N3,
                    "Trông có vẻ…",
                    "ように見える|ようにみえる|ように見え"),
            new Entry("spot_n3_tomiete", "～と見えて", N3,
                    "Dường như…",
                    "と見えて|とみえて"),
            new Entry("spot_n3_sudeni", "～すでに", N3,
                    "Đã…/ Đã… rồi.",
                    "すでに|既に"),
            new Entry("spot_n3_sarani", "～さらに", N3,
                    "Càng…/ … hơn nữa.",
                    "さらに|更に")
    );

    @Override
    public void run(String... args) {
        int added = 0;
        for (Entry e : DICTIONARY) {
            if (subUseRepository.existsByDetectorKey(e.key())) {
                continue;
            }
            GrammarSubUse su = subUseRepository.save(GrammarSubUse.builder()
                    .name(e.pattern())
                    .jlptLevel(e.level())
                    .detectorKey(e.key())
                    .nuanceDescription(e.nuance())
                    .build());
            markerRepository.save(GrammarMarker.builder()
                    .subUse(su)
                    .markerPattern(e.pattern())
                    .detectorSubkey(e.regex())
                    .build());
            added++;
        }
        if (added > 0) {
            log.info("Grammar Spotter N3 dictionary seeded: {} new JLPT patterns", added);
        }
        // Rebuild the Aho-Corasick + regex index so the new patterns are live immediately.
        grammarSpotter.invalidateIndex();
    }
}
