package com.example.starter_project_2025.domain.production.seed;

import com.example.starter_project_2025.domain.production.grammar.GrammarMarker;
import com.example.starter_project_2025.domain.production.grammar.GrammarMarkerRepository;
import com.example.starter_project_2025.domain.production.grammar.GrammarSpotterService;
import com.example.starter_project_2025.domain.production.grammar.GrammarSubUse;
import com.example.starter_project_2025.domain.production.grammar.GrammarSubUseRepository;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.boot.CommandLineRunner;
import org.springframework.core.annotation.Order;
import org.springframework.stereotype.Component;

import java.util.List;

/**
 * Bulk N5 / N4 / N2 / N1 dictionary for the translate-page "Grammar Spotter"
 * ({@link GrammarSpotterService}). Companion to {@link GrammarSpotterN3Seeder};
 * together they extend the small canonical {@link GrammarDictionarySeeder} set to
 * full JLPT coverage. Sourced from the per-level grammar indexes of
 * tiengnhatdongian.com and curated by hand into the two-track model.
 *
 * <h2>De-duplication</h2>
 * The source site lists the same expression under several JLPT levels (N2 in
 * particular repeats much of N3, and the N1 index re-lists many N2 points). To
 * avoid the Spotter firing twice for one surface form, every pattern already
 * covered by {@link GrammarDictionarySeeder}, {@link ProductionSeeder} or
 * {@link GrammarSpotterN3Seeder} is intentionally omitted here — only net-new
 * surface forms are seeded. Bare high-frequency particles (は・が・を・に・の・も・
 * こと・もの・とき…) are skipped too: as plain keywords they fire on nearly every
 * sentence and bury the useful hits.
 *
 * <h2>Track A vs Track B</h2>
 * Same hybrid design as {@link GrammarSpotterN3Seeder}: {@code regex == null} ⇒
 * the stripped pattern becomes an Aho-Corasick keyword (Track A, for invariant
 * expressions); a non-null regex (Track B) is hand-written for conjugating or
 * <i>split</i> patterns that have words in the middle (しか～ない, たり～たり,
 * ようと～まいと…). No LLM at seed-time or runtime.
 *
 * @see GrammarSpotterN3Seeder
 */
@Slf4j
@Component
@Order(103)
@RequiredArgsConstructor
public class GrammarSpotterBulkSeeder implements CommandLineRunner {

    private final GrammarSubUseRepository subUseRepository;
    private final GrammarMarkerRepository markerRepository;
    private final GrammarSpotterService grammarSpotter;

    /** key, display pattern, JLPT level, Vietnamese nuance, detection regex (null ⇒ Track A keyword). */
    private record Entry(String key, String pattern, String level, String nuance, String regex) {}

    private static final List<Entry> DICTIONARY = List.of(
            // ══════════════════════ N5 ══════════════════════
            new Entry("spot_n5_irassharu", "～いらっしゃる", "N5",
                    "Kính ngữ: có/ ở/ đi/ đến.", "いらっしゃ"),
            new Entry("spot_n5_mashou", "～ましょう", "N5",
                    "Chúng ta hãy cùng…/ … nhé.", "ましょう"),
            new Entry("spot_n5_gahoshii", "～がほしいです", "N5",
                    "Tôi muốn (cái gì đó)…", "がほしい|が欲しい"),
            new Entry("spot_n5_onegaishimasu", "～おねがいします", "N5",
                    "Hãy, làm ơn…", "お願いします|おねがいします"),
            new Entry("spot_n5_naidekudasai", "～ないでください", "N5",
                    "Đừng/ Xin đừng (làm gì).", "ないでください|ないで下さい"),
            new Entry("spot_n5_deshou", "～でしょう／だろう", "N5",
                    "Có lẽ…/ … phải không?", "でしょう|だろう"),
            new Entry("spot_n5_shika_nai", "しか～ない", "N5",
                    "Chỉ…/ Chỉ có…/ Chỉ còn…", "しか.{0,10}な(い|かった)|しかない"),
            new Entry("spot_n5_nakutemoii", "～なくてもいいです", "N5",
                    "Không cần, không phải (làm gì).", "なくてもいい|なくても良い|なくてもよ"),
            new Entry("spot_n5_atode", "～あとで／あとに", "N5",
                    "Sau…/ Sau khi (đã)…", "あとで|あとに|後で|後に"),
            new Entry("spot_n5_mada_teimasen", "まだ～ていません", "N5",
                    "Vẫn chưa…", "まだ.{0,8}ていま|まだ.{0,8}てない"),
            new Entry("spot_n5_temitekudasai", "～てみてください", "N5",
                    "Xin hãy thử…", "てみてください|て見てください"),
            new Entry("spot_n5_hodo_nai", "～ほど～ない", "N5",
                    "Không bằng/ Không… như…", "ほど.{0,10}な(い|かった)"),
            new Entry("spot_n5_toonaji", "～と同じ", "N5",
                    "Giống/ Giống như/ Cùng…", "と同じ|とおなじ"),
            new Entry("spot_n5_nakadeichiban", "～のなかでいちばん", "N5",
                    "Trong… thì… là nhất.", "中でいちばん|なかでいちばん|中で一番"),
            new Entry("spot_n5_tari_tari", "～たり～たりする", "N5",
                    "Nào là… nào là…/ Lúc thì… lúc thì…", "[ただ]り.{0,12}[ただ]り"),
            new Entry("spot_n5_maeni", "～まえに", "N5",
                    "Trước…/ Trước khi…", "まえに|前に"),
            new Entry("spot_n5_tekara", "～てから", "N5",
                    "Sau khi…/ Từ khi…", "てから"),
            new Entry("spot_n5_toomoimasu", "～とおもいます", "N5",
                    "Tôi nghĩ rằng, cho rằng…", "と思います|とおもいます|と思う"),
            new Entry("spot_n5_toiimasu", "～といいます", "N5",
                    "Gọi là/ Nói là…", "といいます|と言います"),
            new Entry("spot_n5_ikagadesuka", "～いかがですか", "N5",
                    "… thế nào?", "いかがですか"),
            new Entry("spot_n5_dearu", "～である", "N5",
                    "Biểu hiện định nghĩa (văn viết).", "である(。|、|こと|もの|と|の)"),

            // ══════════════════════ N4 ══════════════════════
            new Entry("spot_n4_ndesu", "～んです", "N4",
                    "Giải thích/ nhấn mạnh lý do.", "んです|のです|んだ(。|、|よ|ね|けど)"),
            new Entry("spot_n4_nasai", "～なさい", "N4",
                    "Mệnh lệnh nhẹ (hãy…).", "なさい"),
            new Entry("spot_n4_teitadakemasenka", "～ていただけませんか", "N4",
                    "Bạn có thể… giúp tôi được không?", "ていただけませんか|ていただけ"),
            new Entry("spot_n4_shi_shi", "～し、～し", "N4",
                    "Liệt kê lý do/ đặc điểm (vừa… vừa…).", "し、.{0,15}し(、|。)"),
            new Entry("spot_n4_tearu", "～てある", "N4",
                    "Trạng thái do ai đó đã làm.", "てある|てあります|である(?=状態)"),
            new Entry("spot_n4_yotei", "～予定です", "N4",
                    "Dự định/ kế hoạch…", "予定(です|だ|で|の)"),
            new Entry("spot_n4_temokamawanai", "～てもかまわない", "N4",
                    "Được (làm gì) cũng không sao.", "てもかまわ|ても構わ|でもかまわ"),
            new Entry("spot_n4_toyomimasu", "～と読みます", "N4",
                    "Đọc là…", "と読みます|とよみます"),
            new Entry("spot_n4_toiuimi", "～という意味です", "N4",
                    "Có nghĩa là…", "という意味|といういみ"),
            new Entry("spot_n4_toitteiru", "～と言っている", "N4",
                    "Nói rằng/ bảo rằng…", "と言っている|と言ってる|といっている"),
            new Entry("spot_n4_toiimashita", "～と言いました", "N4",
                    "Đã nói rằng…", "と言いました|といいました"),
            new Entry("spot_n4_tochuude", "～途中で", "N4",
                    "Giữa chừng/ trên đường…", "途中で|とちゅうで|途中に"),
            new Entry("spot_n4_kadouka", "～かどうか", "N4",
                    "Có… hay không…", "かどうか"),
            new Entry("spot_n4_temiru", "～てみる", "N4",
                    "Thử (làm gì)…", "てみる|てみます|てみた|てみよう"),
            new Entry("spot_n4_tekimasu", "～てきます", "N4",
                    "Đi (làm gì) rồi quay lại; bắt đầu…", "てきます|てくる|てきた"),
            new Entry("spot_n4_souni", "～そうに／そうな", "N4",
                    "Trông có vẻ…", "そうに|そうな|そうだった"),
            new Entry("spot_n4_gasuru", "～がする", "N4",
                    "Có cảm giác/ mùi/ âm thanh…", "がする|がします|がした"),
            new Entry("spot_n4_baaiwa", "～場合は", "N4",
                    "Trong trường hợp…", "場合(は|に|の|、)|ばあいは"),

            // ══════════════════════ N2 ══════════════════════
            new Entry("spot_n2_nisaishite", "～に際して", "N2",
                    "Khi/ Nhân dịp/ Nhân cơ hội…", "に際して|にさいして|に際し"),
            new Entry("spot_n2_niatatte", "～にあたって", "N2",
                    "Khi/ Lúc/ Nhân dịp…", "にあたって|に当たって|にあたり"),
            new Entry("spot_n2_kato omouto", "～かと思うと", "N2",
                    "Vừa mới… mà đã…", "かと思うと|かとおもうと|かと思えば"),
            new Entry("spot_n2_kanaikanouchini", "～か～ないかのうちに", "N2",
                    "Chưa kịp xong… thì…", "ないかのうちに"),
            new Entry("spot_n2_iyoiyo", "～いよいよ", "N2",
                    "Ngày càng/ Sắp/ Đã sắp đến…", "いよいよ"),
            new Entry("spot_n2_kato iuto", "～かというと", "N2",
                    "Nếu nói là…/ Nói về việc có…", "かというと|かと言うと"),
            new Entry("spot_n2_i) ittai", "～いったい", "N2",
                    "Rốt cuộc là…/ Không biết là…", "いったい|一体"),
            new Entry("spot_n2_tekoso", "～てこそ", "N2",
                    "Chỉ khi… thì mới…", "てこそ|でこそ"),
            new Entry("spot_n2_n=naikagiri", "～ない限り", "N2",
                    "Nếu không/ Chừng nào chưa…", "ない限り|ないかぎり"),
            new Entry("spot_n2_niwaoyobanai", "～には及ばない", "N2",
                    "Không đến mức phải…", "には及ばない|にはおよばない"),
            new Entry("spot_n2_naidemonai", "～ないでもない", "N2",
                    "Không phải là không…", "ないでもない|ないものでもない"),
            new Entry("spot_n2_tesshouganai", "～てしょうがない", "N2",
                    "Không thể chịu nổi…", "てしょうがない|てしようがない"),
            new Entry("spot_n2_kaneru", "～かねる", "N2",
                    "Không thể/ Khó mà…", "かねる|かねます|かね(?=ない)"),
            new Entry("spot_n2_shidaideha", "～次第では", "N2",
                    "Tùy thuộc vào thì cũng có khi…", "次第では|しだいでは"),
            new Entry("spot_n2_karasuruto", "～からすると", "N2",
                    "Căn cứ trên…/ Xét từ…", "からすると|からすれば"),
            new Entry("spot_n2_uru", "～得る", "N2",
                    "Có thể/ Có khả năng xảy ra…", "得る(。|、|こと|の|が)|うる(。|、|こと)|えます"),
            new Entry("spot_n2_enai", "～得ない", "N2",
                    "Không thể/ Không có khả năng…", "得ない|えない(?=。|、)|うべからず"),
            new Entry("spot_n2_wabetsuto shite", "～は別として", "N2",
                    "… thì không xét tới/ … thì khác.", "は別として|はべつとして"),
            new Entry("spot_n2_nisuginai", "～に過ぎない", "N2",
                    "Chỉ là…/ Chỉ đơn giản là…", "に過ぎない|にすぎない"),
            new Entry("spot_n2_teha irarenai", "～てはいられない", "N2",
                    "Không thể cứ… mãi được.", "てはいられない|ではいられない|てらんない"),
            new Entry("spot_n2_tsutsu", "～つつ", "N2",
                    "Vừa… vừa…/ Trong lúc…", "つつ(、|。|ある|も)"),
            new Entry("spot_n2_tsutsuaru", "～つつある", "N2",
                    "Đang dần dần…", "つつある"),
            new Entry("spot_n2_karashite", "～からして", "N2",
                    "Ngay cả… đã…/ Xét từ…", "からして"),
            new Entry("spot_n2_shidaide", "～次第で", "N2",
                    "Tùy theo…/ Tùy thuộc…", "次第で|しだいで"),
            new Entry("spot_n2_shidai", "～次第", "N2",
                    "Ngay sau khi… thì…", "次第(だ|です|に|。)|しだい(だ|です)"),
            new Entry("spot_n2_kagiri", "～限り", "N2",
                    "Chừng nào còn/ Trong phạm vi…", "限り(、|。|は|で)|かぎり(、|。)"),
            new Entry("spot_n2_oukamaika", "～(よ)うか～まいか", "N2",
                    "Có nên… hay không…", "うか.{0,8}まいか|ようか.{0,8}まいか"),
            new Entry("spot_n2_nikagirazu", "～に限らず", "N2",
                    "Không chỉ… mà cả…", "に限らず|にかぎらず"),
            new Entry("spot_n2_nominarazu", "～のみならず", "N2",
                    "Không chỉ… mà còn…", "のみならず"),
            new Entry("spot_n2_nikoshita", "～に越したことはない", "N2",
                    "… thì tốt hơn/ là tốt nhất.", "に越したことはない|にこしたことはない"),
            new Entry("spot_n2_nihokanaranai", "～にほかならない", "N2",
                    "Chính là…/ Không gì khác ngoài…", "にほかならない|に他ならない"),
            new Entry("spot_n2_nikagitte", "～に限って", "N2",
                    "Đúng vào… thì…/ Chỉ riêng…", "に限って|にかぎって"),
            new Entry("spot_n2_mai", "～まい", "N2",
                    "Sẽ không…/ Quyết không…", "まい(。|、|と|か|し)"),
            new Entry("spot_n2_womegutte", "～をめぐって", "N2",
                    "Xoay quanh…/ Xung quanh…", "をめぐって|を巡って|をめぐる"),
            new Entry("spot_n2_nikaketewa", "～にかけては", "N2",
                    "Về mặt… thì…/ Trong lĩnh vực…", "にかけては"),
            new Entry("spot_n2_nomotode", "～のもとで", "N2",
                    "Dưới sự…/ Nhờ vào…", "のもとで|の下で|のもとに"),
            new Entry("spot_n2_nisotte", "～に沿って", "N2",
                    "Dọc theo…/ Theo đúng…", "に沿って|にそって|に沿った"),
            new Entry("spot_n2_nioujite", "～に応じて", "N2",
                    "Dựa vào…/ Tùy theo…", "に応じて|におうじて|に応じた"),
            new Entry("spot_n2_nitsuke", "～につけ", "N2",
                    "Cứ mỗi lần… là lại…", "につけ"),
            new Entry("spot_n2_mokamawazu", "～もかまわず", "N2",
                    "Không màng tới…/ Bất chấp…", "もかまわず|も構わず"),
            new Entry("spot_n2_nimokakawarazu", "～にもかかわらず", "N2",
                    "Mặc dù… nhưng…", "にもかかわらず|にも関わらず|にも拘らず"),
            new Entry("spot_n2_nikakawarazu", "～にかかわらず", "N2",
                    "Bất kể…/ Không phân biệt…", "にかかわらず|に関わらず"),
            new Entry("spot_n2_wotowazu", "～を問わず", "N2",
                    "Không kể…/ Bất kể…", "を問わず|をとわず"),
            new Entry("spot_n2_toitta", "～といった", "N2",
                    "Ví dụ như…/ Những thứ như…", "といった"),
            new Entry("spot_n2_nishiro_nishiro", "～にしろ～にしろ", "N2",
                    "Dù là… hay…", "にしろ.{0,12}にしろ|にせよ.{0,12}にせよ"),
            new Entry("spot_n2_watomokaku", "～はともかく", "N2",
                    "Khoan hãy nói đến…", "はともかく"),
            new Entry("spot_n2_kkonai", "～っこない", "N2",
                    "Nhất định là không…", "っこない|こない(?=。|、|よ)"),
            new Entry("spot_n2_wasateoki", "～はさておき", "N2",
                    "Khoan hãy nói đến…/ Tạm gác…", "はさておき"),
            new Entry("spot_n2_dokorodewanai", "～どころではない", "N2",
                    "Không phải lúc/ Không còn tâm trí…", "どころではない|どころじゃない"),
            new Entry("spot_n2_toiumonodewanai", "～というものではない", "N2",
                    "Không phải… (cứ thế là được)…", "というものではない|というものでもない"),
            new Entry("spot_n2_tohaiumonono", "～とはいうものの", "N2",
                    "Tuy… nhưng…", "とはいうものの|とは言うものの"),
            new Entry("spot_n2_monono", "～ものの", "N2",
                    "Tuy là… nhưng…", "ものの(、|。)"),
            new Entry("spot_n2_tonattara", "～となったら", "N2",
                    "Nếu mà…/ Cứ… thì…", "となったら|となると"),
            new Entry("spot_n2_nikotaete", "～に応えて", "N2",
                    "Đáp lại…/ Đáp ứng…", "に応えて|にこたえて|に応える"),
            new Entry("spot_n2_oumononara", "～(よ)うものなら", "N2",
                    "Nếu lỡ… thì…", "ようものなら|うものなら"),
            new Entry("spot_n2_naikotoniwa", "～ないことには", "N2",
                    "Nếu không… thì…", "ないことには"),
            new Entry("spot_n2_wonukinishite", "～を抜きにして", "N2",
                    "Nếu bỏ qua…/ Không tính đến…", "を抜きにして|をぬきにして|抜きで"),
            new Entry("spot_n2_amari", "～あまり", "N2",
                    "Vì quá…/ Vì rất…", "あまり(、|。|に)|余り(、|に)"),
            new Entry("spot_n2_nokotodakara", "～のことだから", "N2",
                    "Vì là… nên (chắc)…", "のことだから"),
            new Entry("spot_n2_bakarini", "～ばかりに", "N2",
                    "Chỉ tại/ Chỉ vì…", "ばかりに"),
            new Entry("spot_n2_gatai", "～がたい", "N2",
                    "Khó mà…", "がたい|難い(?=。|、|こと)"),
            new Entry("spot_n2_tedemo", "～てでも", "N2",
                    "Cho dù phải… cũng…", "てでも|ででも"),
            new Entry("spot_n2_kanenai", "～かねない", "N2",
                    "Có khả năng…/ Có thể sẽ (xấu)…", "かねない|兼ねない"),
            new Entry("spot_n2_nisouinai", "～に相違ない", "N2",
                    "Chắc chắn/ Đúng là…", "に相違ない|にそういない"),
            new Entry("spot_n2_uewa", "～上は", "N2",
                    "Một khi đã… thì…", "上は|うえは"),
            new Entry("spot_n2_ijou", "～以上", "N2",
                    "Một khi đã/ Vì là…", "以上(は|、|。|だ)|いじょうは"),
            new Entry("spot_n2_kotodashi", "～ことだし", "N2",
                    "Vì…/ Bởi vì… nên…", "ことだし"),
            new Entry("spot_n2_nitsuki", "～につき", "N2",
                    "Vì… nên/ Do…", "につき"),
            new Entry("spot_n2_ageku", "～あげく", "N2",
                    "Sau một hồi… thì cuối cùng…", "あげく|挙句|あげくに"),
            new Entry("spot_n2_wokeikini", "～を契機に", "N2",
                    "Nhân dịp…/ Lấy… làm bước ngoặt.", "を契機に|をけいきに"),
            new Entry("spot_n2_sueni", "～末に", "N2",
                    "Sau khi… (cuối cùng)…", "末に|すえに|末の"),
            new Entry("spot_n2_madeshite", "～までして", "N2",
                    "Đến mức…/ Tới mức (phải)…", "までして"),
            new Entry("spot_n2_zujimai", "～ずじまい", "N2",
                    "Rốt cuộc đã không kịp…", "ずじまい|ずじまいだ"),
            new Entry("spot_n2_dakeatte", "～だけあって", "N2",
                    "Đúng là…/ Thảo nào…", "だけあって|だけのことはあって"),
            new Entry("spot_n2_dehanaika", "～ではないか", "N2",
                    "Không phải… sao/ … đấy chứ.", "ではないか|じゃないか"),
            new Entry("spot_n2_naidehairarenai", "～ないではいられない", "N2",
                    "Không thể không…", "ないではいられない|ずにはいられない"),
            new Entry("spot_n2_monogaaru", "～ものがある", "N2",
                    "Có cảm giác/ có cái gì đó…", "ものがある"),
            new Entry("spot_n2_naimonoka", "～ないものか", "N2",
                    "Liệu có cách nào…?", "ないものか|ないものかと"),
            new Entry("spot_n2_taimonoda", "～たいものだ", "N2",
                    "Thật sự muốn/ Ước gì…", "たいものだ"),
            new Entry("spot_n2_kotonaku", "～ことなく", "N2",
                    "Không…/ Mà không…", "ことなく"),
            new Entry("spot_n2_nuku", "～抜く", "N2",
                    "Làm tới cùng…", "抜く|ぬく(?=。|、|こと)"),
            new Entry("spot_n2_dokoroka", "～どころか", "N2",
                    "Không những… mà ngược lại…", "どころか"),
            new Entry("spot_n2_dakeni", "～だけに", "N2",
                    "Chính vì… nên (càng)…", "だけに"),
            new Entry("spot_n2_kotoni", "～ことに", "N2",
                    "Thật là…/ Thật… làm sao.", "ことに(、|。)"),
            new Entry("spot_n2_uemono", "～上（に）", "N2",
                    "Hơn nữa, bên cạnh đó…", "上に(、|。|さらに)|うえに"),
            new Entry("spot_n2_nagara_gyaku", "～ながら（も）", "N2",
                    "Tuy… nhưng… (nghịch).", "ながらも|ながら(?=、)"),
            new Entry("spot_n2_dano_dano", "～だの～だの", "N2",
                    "Nào là… nào là…", "だの.{0,12}だの"),
            new Entry("spot_n2_nisakidatte", "～に先立って", "N2",
                    "Trước…/ Trước khi…", "に先立って|にさきだって|に先立ち"),
            new Entry("spot_n2_zunisumu", "～ずにすむ", "N2",
                    "Khỏi phải/ Tránh được…", "ずにすむ|ずに済む|ないですむ"),

            // ══════════════════════ N1 ══════════════════════
            new Entry("spot_n1_nitaenai", "～にたえない", "N1",
                    "Không chịu nổi/ Không đáng/ Vô cùng…", "にたえない|に耐えない|に堪えない"),
            new Entry("spot_n1_nari", "～なり", "N1",
                    "Vừa mới… thì đã lập tức…", "なり(、|。|に|や)(?=.{0,4}た)"),
            new Entry("spot_n1_tsu_tsu", "～つ～つ", "N1",
                    "Khi thì… khi thì…", "つ.{0,6}つ(、|。|し)"),
            new Entry("spot_n1_monoo", "～ものを", "N1",
                    "Vậy mà/ Thế mà/ Giá mà…", "ものを(。|、)"),
            new Entry("spot_n1_atteno", "～あっての", "N1",
                    "Tồn tại được là nhờ…", "あっての"),
            new Entry("spot_n1_nisokushite", "～に即して", "N1",
                    "Theo đúng…/ Phù hợp với…", "に即して|にそくして|に即した"),
            new Entry("spot_n1_nimomashite", "～にもまして", "N1",
                    "Hơn cả…/ Càng… hơn.", "にもまして|にも増して"),
            new Entry("spot_n1_kiwamaru", "～極まる", "N1",
                    "Rất…/ Cực kỳ…/ Vô cùng…", "極まる|きわまる|極まりない"),
            new Entry("spot_n1_zunihaokanai", "～ずにはおかない", "N1",
                    "Thế nào cũng…/ Nhất định sẽ…", "ずにはおかない|ないではおかない"),
            new Entry("spot_n1_nokiwami", "～の極み", "N1",
                    "Hết sức…/ Cực kỳ…", "の極み|のきわみ"),
            new Entry("spot_n1_bekarazaru", "～べからざる", "N1",
                    "Không được/ Không thể (được phép)…", "べからざる|べからず"),
            new Entry("spot_n1_meku", "～めく", "N1",
                    "Có vẻ…/ Nhuốm màu…", "めく(。|、|いた|いて)|めいた"),
            new Entry("spot_n1_sura", "～すら", "N1",
                    "Ngay cả/ Đến cả/ Thậm chí…", "すら(、|。|ない|できない)"),
            new Entry("spot_n1_noitari", "～の至り", "N1",
                    "Vô cùng…/ Cực kỳ…", "の至り|のいたり"),
            new Entry("spot_n1_wooite", "～をおいて", "N1",
                    "Ngoài… ra thì (không)…", "をおいて|を置いて(?=.{0,6}ない)"),
            new Entry("spot_n1_naradeha", "～ならでは", "N1",
                    "Chỉ có… mới có thể…", "ならでは"),
            new Entry("spot_n1_woyosoni", "～をよそに", "N1",
                    "Mặc kệ/ Bất chấp…", "をよそに"),
            new Entry("spot_n1_nbakaridi", "～んばかりだ", "N1",
                    "Tưởng chừng như/ Gần như…", "んばかり"),
            new Entry("spot_n1_tomonaku", "～ともなく", "N1",
                    "Một cách vô thức/ bâng quơ…", "ともなく|ともなしに"),
            new Entry("spot_n1_kiraigaaru", "～きらいがある", "N1",
                    "Có xu hướng/ Thường hay…", "きらいがある|嫌いがある"),
            new Entry("spot_n1_gatera", "～がてら", "N1",
                    "Nhân tiện/ Tiện thể…", "がてら"),
            new Entry("spot_n1_tohaie", "～とは言え", "N1",
                    "Mặc dù nói là…/ Tuy là…", "とは言え|とはいえ"),
            new Entry("spot_n1_toiedomo", "～といえども", "N1",
                    "Cho dù là/ Ngay cả…", "といえども|と言えども"),
            new Entry("spot_n1_tarasaigo", "～たら最後", "N1",
                    "Một khi đã… thì (nhất định)…", "たら最後|たらさいご|たが最後"),
            new Entry("spot_n1_toattewa", "～とあっては", "N1",
                    "Nếu (trong tình huống)… thì…", "とあっては"),
            new Entry("spot_n1_tokitara", "～ときたら", "N1",
                    "Nhắc đến… (thì)…", "ときたら"),
            new Entry("spot_n1_nihaataranai", "～にはあたらない", "N1",
                    "Không đáng để…/ Chẳng đáng…", "にはあたらない|には当たらない"),
            new Entry("spot_n1_tomonaruto", "～ともなると", "N1",
                    "Một khi đã đến mức…", "ともなると|ともなれば"),
            new Entry("spot_n1_nikakawaru", "～にかかわる", "N1",
                    "Ảnh hưởng tới…/ Liên quan đến (sống còn)…", "にかかわる|に関わる"),
            new Entry("spot_n1_nakushite", "～なくして", "N1",
                    "Nếu không có…", "なくして"),
            new Entry("spot_n1_nashini", "～なしに", "N1",
                    "Mà không…/ Không có…", "なしに"),
            new Entry("spot_n1_hameninaru", "～羽目になる", "N1",
                    "Rơi vào tình huống (phải)…", "羽目になる|はめになる"),
            new Entry("spot_n1_ikanaru", "～いかなる", "N1",
                    "Dẫu… thế nào cũng…", "いかなる"),
            new Entry("spot_n1_socchinokede", "～そっちのけで", "N1",
                    "Hoàn toàn bỏ mặc…", "そっちのけ"),
            new Entry("spot_n1_ngatame", "～んがため", "N1",
                    "Để/ Vì mục đích…", "んがため"),
            new Entry("spot_n1_bakoso", "～ばこそ", "N1",
                    "Chính vì… mới…", "ばこそ"),
            new Entry("spot_n1_toatte", "～とあって", "N1",
                    "Bởi vì/ Vì/ Do…", "とあって"),
            new Entry("spot_n1_dehaarumaishi", "～ではあるまいし", "N1",
                    "Đâu phải là…", "ではあるまいし|じゃあるまいし"),
            new Entry("spot_n1_temae", "～手前", "N1",
                    "Vì (sĩ diện/ vị thế)…", "手前(、|。)|てまえ(、|。)"),
            new Entry("spot_n1_temiruya", "～と見るや", "N1",
                    "Vừa thấy… thì lập tức…", "と見るや|とみるや"),
            new Entry("spot_n1_woshirimeni", "～を尻目に", "N1",
                    "Mặc kệ/ Không quan tâm…", "を尻目に|をしりめに"),
            new Entry("spot_n1_nrini", "～なりに", "N1",
                    "Theo cách của…/ Tùy theo…", "なりに|なりの"),
            new Entry("spot_n1_madenomonai", "～までもない", "N1",
                    "Chưa tới mức phải…", "までもない|までもなく"),
            new Entry("spot_n1_tomirareru", "～と見られる", "N1",
                    "Được cho là…/ Người ta tin rằng…", "と見られる|とみられる"),
            new Entry("spot_n1_gurumi", "～ぐるみ", "N1",
                    "Toàn bộ/ Toàn thể…", "ぐるみ"),
            new Entry("spot_n1_yuue", "～ゆえ", "N1",
                    "Do/ Vì… nên…", "ゆえ(に|の|、|。)|故(に|の)"),
            new Entry("spot_n1_nikatakunai", "～にかたくない", "N1",
                    "Không khó để…", "にかたくない|に難くない"),
            new Entry("spot_n1_beku", "～べく", "N1",
                    "Để/ Để có thể…", "べく(、|。|して)"),
            new Entry("spot_n1_outomaito", "～ようと～まいと", "N1",
                    "Dù có… hay không…", "ようと.{0,8}まいと|うと.{0,8}まいと"),
            new Entry("spot_n1_toattaba", "～とあれば", "N1",
                    "Nếu… thì (sẵn sàng)…", "とあれば"),
            new Entry("spot_n1_toomoikiya", "～と思いきや", "N1",
                    "Cứ tưởng là… nhưng thực ra…", "と思いきや|とおもいきや"),
            new Entry("spot_n1_katawara", "～かたわら", "N1",
                    "Bên cạnh/ Vừa… vừa…", "かたわら|傍ら"),
            new Entry("spot_n1_katagata", "～かたがた", "N1",
                    "Nhân tiện/ Sẵn tiện…", "かたがた"),
            new Entry("spot_n1_narainai", "～ならいざしらず", "N1",
                    "… thì đã đành (còn)…", "ならいざしらず|はいざしらず"),
            new Entry("spot_n1_womonotomosezu", "～をものともせず", "N1",
                    "Bất chấp/ Mặc cho…", "をものともせず"),
            new Entry("spot_n1_wokinjienai", "～を禁じ得ない", "N1",
                    "Không kìm nén được…", "を禁じ得ない|をきんじえない"),
            new Entry("spot_n1_ikanniyorazu", "～いかんによらず", "N1",
                    "Bất kể/ Dù với bất cứ…", "いかんによらず|いかんにかかわらず"),
            new Entry("spot_n1_ikan", "～いかん", "N1",
                    "Tùy vào/ Tùy thuộc vào…", "いかんだ|いかんで|いかんによって|いかんによっては"),
            new Entry("spot_n1_toii_toii", "～といい～といい", "N1",
                    "Cả… lẫn…/ Cũng… cũng…", "といい.{0,12}といい"),
            new Entry("spot_n1_naramadashi", "～ならまだしも", "N1",
                    "Nếu (chỉ)… thì còn đỡ.", "ならまだしも|まだしも"),
            new Entry("spot_n1_nimohodogaaru", "～にもほどがある", "N1",
                    "Quá/ Quá mức/ Quá đà…", "にもほどがある|にも程がある"),
            new Entry("spot_n1_wo iikotoni", "～のをいいことに", "N1",
                    "Lợi dụng việc…", "のをいいことに|をいいことに"),
            new Entry("spot_n1_wa_wa", "～わ～わ", "N1",
                    "Nào là… nào là… (than)…", "わ.{0,10}わで|わ.{0,8}わ(、|。)"),
            new Entry("spot_n1_iwaba", "～言わば", "N1",
                    "Có thể nói…/ Ví như là…", "言わば|いわば"),
            new Entry("spot_n1_deare", "～であれ", "N1",
                    "Dù là/ Cho dù…", "であれ(、|。|.{0,10}であれ)"),
            new Entry("spot_n1_nari_nari", "～なり～なり", "N1",
                    "… hoặc là… hoặc là…", "なり.{0,12}なり(、|。|し)"),
            new Entry("spot_n1_mosarinagara", "～もさることながら", "N1",
                    "… thì hẳn nhiên rồi (mà còn)…", "もさることながら|さることながら"),
            new Entry("spot_n1_waora", "～はおろか", "N1",
                    "Đừng nói là…, ngay cả…", "はおろか"),
            new Entry("spot_n1_womotte", "～をもって", "N1",
                    "Bằng/ Lấy… làm…", "をもって|を以て"),
            new Entry("spot_n1_nikagittakoto", "～に限ったことではない", "N1",
                    "… không phải chỉ là…", "に限ったことではない|にかぎったことではない"),
            new Entry("spot_n1_naitomokagiranai", "～ないとも限らない", "N1",
                    "Không chắc là sẽ không…", "ないとも限らない|ないともかぎらない"),
            new Entry("spot_n1_wokagirini", "～を限りに", "N1",
                    "Hết/ Đến hết…", "を限りに|をかぎりに"),
            new Entry("spot_n1_makuru", "～まくる", "N1",
                    "… suốt/ Cứ liên tục…", "まくる|まくった|まくり"),
            new Entry("spot_n1_madeda", "～までだ", "N1",
                    "Thì đành/ Chỉ… (mà thôi).", "までだ|までのことだ"),
            new Entry("spot_n1_bekumonai", "～べくもない", "N1",
                    "Không thể nào…", "べくもない"),
            new Entry("spot_n1_tohikikaeni", "～と引き換えに", "N1",
                    "Để đổi lấy…", "と引き換えに|とひきかえに"),
            new Entry("spot_n1_nihikikae", "～に引き換え", "N1",
                    "Trái ngược với…", "に引き換え|にひきかえ"),
            new Entry("spot_n1_niitatte", "～に至って", "N1",
                    "Đến khi… mới…", "に至って|にいたって|に至っては|に至っても"),
            new Entry("spot_n1_niitarumade", "～に至るまで", "N1",
                    "Cho đến/ Đến cả/ Đến mức…", "に至るまで|にいたるまで"),
            new Entry("spot_n1_wokawakirini", "～を皮切りに", "N1",
                    "Bắt đầu với…", "を皮切りに|をかわきりに"),
            new Entry("spot_n1_sobakara", "～そばから", "N1",
                    "Vừa mới… thì lập tức (lại)…", "そばから"),
            new Entry("spot_n1_tekaratoiumono", "～てからというもの", "N1",
                    "Kể từ khi…", "てからというもの|てからというものは"),
            new Entry("spot_n1_niatte", "～にあって", "N1",
                    "Ở trong (hoàn cảnh) đó…", "にあって(、|。|は|も)"),
            new Entry("spot_n1_gahayaika", "～が早いか", "N1",
                    "Vừa mới… thì đã…", "が早いか|がはやいか"),
            new Entry("spot_n1_nishite", "～にして", "N1",
                    "Chỉ trong/ Chỉ mới/ Phải đến…", "にして(はじめて|こそ|なお)")
    );

    @Override
    public void run(String... args) {
        int added = 0;
        for (Entry e : DICTIONARY) {
            if (subUseRepository.existsByDetectorKey(e.key())) {
                continue;
            }
            GrammarSubUse su = subUseRepository.save(GrammarSubUse.builder()
                    .name(e.pattern())
                    .jlptLevel(e.level())
                    .detectorKey(e.key())
                    .nuanceDescription(e.nuance())
                    .build());
            markerRepository.save(GrammarMarker.builder()
                    .subUse(su)
                    .markerPattern(e.pattern())
                    .detectorSubkey(e.regex())
                    .build());
            added++;
        }
        if (added > 0) {
            log.info("Grammar Spotter bulk N5/N4/N2/N1 dictionary seeded: {} new JLPT patterns", added);
        }
        grammarSpotter.invalidateIndex();
    }
}
