package com.example.starter_project_2025.init;

import com.example.starter_project_2025.init.annotation.ResourceMenu;
import com.example.starter_project_2025.system.menu.module.Module;
import com.example.starter_project_2025.system.menu.module.ModuleRepository;
import com.example.starter_project_2025.system.menu.module_groups.ModuleGroup;
import com.example.starter_project_2025.system.menu.module_groups.ModuleGroupRepository;
import jakarta.transaction.Transactional;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.beans.factory.config.BeanDefinition;
import org.springframework.boot.CommandLineRunner;
import org.springframework.context.annotation.ClassPathScanningCandidateComponentProvider;
import org.springframework.core.annotation.Order;
import org.springframework.core.type.filter.AnnotationTypeFilter;
import org.springframework.stereotype.Component;

import java.util.HashSet;
import java.util.List;
import java.util.Locale;
import java.util.Set;

@Slf4j
@Order(10)
@Component
@RequiredArgsConstructor
public class AutoMenuInitializer implements CommandLineRunner {

    private final ModuleRepository moduleRepository;
    private final ModuleGroupRepository groupRepository;

    private static final String BASE_PACKAGE = "com.example";

    @Override
    @Transactional
    public void run(String... args) throws Exception {

        log.info("Starting Auto Menu Initialization...");

        ClassPathScanningCandidateComponentProvider scanner =
                new ClassPathScanningCandidateComponentProvider(false);

        scanner.addIncludeFilter(new AnnotationTypeFilter(ResourceMenu.class));

        Set<BeanDefinition> candidates =
                scanner.findCandidateComponents(BASE_PACKAGE);

        // Track which URLs are still backed by a live @ResourceMenu so we
        // can deactivate modules whose source annotation got removed
        // (avoids broken sidebar links after a feature is deleted from BE
        // but its Module row persists in MySQL / a long-lived dev DB).
        Set<String> liveUrls = new HashSet<>();

        for (var candidate : candidates) {

            Class<?> clazz = Class.forName(candidate.getBeanClassName());

            ResourceMenu menu = clazz.getAnnotation(ResourceMenu.class);

            String url = normalizeUrl(menu.url());
            liveUrls.add(url);

            generateMenu(clazz, menu);
        }

        deactivateStaleModules(liveUrls);

        log.info("Auto Menu Initialization completed.");
    }

    /**
     * Mark any active module whose URL is no longer backed by a live
     * {@code @ResourceMenu} annotation as inactive. We don't hard-delete
     * because the row may still be referenced by audit logs / saved
     * views; flipping {@code isActive=false} just hides it from the
     * sidebar query, which is what callers want.
     */
    private void deactivateStaleModules(Set<String> liveUrls) {
        List<Module> all = moduleRepository.findAll();
        int touched = 0;
        for (Module m : all) {
            String url = m.getUrl();
            if (url == null) continue;
            // Skip modules that were created manually (no auto-gen marker).
            // Auto-created modules have "Auto generated menu for ..." in
            // their description — only these are eligible for cleanup.
            String desc = m.getDescription();
            boolean autoGenerated = desc != null && desc.startsWith("Auto generated menu for");
            if (!autoGenerated) continue;

            boolean shouldBeActive = liveUrls.contains(url);
            if (Boolean.TRUE.equals(m.getIsActive()) && !shouldBeActive) {
                m.setIsActive(false);
                moduleRepository.save(m);
                touched++;
                log.info("Deactivated stale auto-menu [{}] -> {}", m.getTitle(), url);
            }
        }
        if (touched > 0) {
            log.info("AutoMenuInitializer deactivated {} stale module(s)", touched);
        }
    }

    private void generateMenu(Class<?> clazz, ResourceMenu menu) {

        String url = normalizeUrl(menu.url());

        Module module = moduleRepository.findByUrl(url).orElseGet(Module::new);
        boolean isNew = module.getId() == null;

        ModuleGroup group = getOrCreateGroup(menu.group());

        module.setModuleGroup(group);
        module.setTitle(menu.title());
        module.setUrl(url);
        module.setIcon(menu.icon());
        module.setDisplayOrder(menu.order());
        module.setRequiredPermission(normalizePermission(menu.permission()));
        // Prefer the annotation's human description (surfaced as the breadcrumb
        // / card ⓘ tooltip). Fall back to the auto-gen marker only when absent
        // so legacy stale-detection (deactivateStaleModules) still recognises
        // annotation-less rows.
        String description = menu.description();
        module.setDescription(
                (description == null || description.isBlank())
                        ? "Auto generated menu for " + clazz.getSimpleName()
                        : description);
        module.setIsActive(true);

        moduleRepository.save(module);

        if (isNew) {
            log.info("Created menu [{}] -> {}", menu.title(), url);
            return;
        }

        log.info("Synchronized menu [{}] -> {}", menu.title(), url);
    }

    private ModuleGroup getOrCreateGroup(String groupName) {

        return groupRepository.findByName(groupName)
                .orElseGet(() -> {

                    ModuleGroup group = new ModuleGroup();

                    group.setName(groupName);
                    group.setDescription("Auto generated group");
                    group.setDisplayOrder(0);
                    group.setIsActive(true);

                    ModuleGroup saved = groupRepository.save(group);

                    log.info("Created module group: {}", groupName);

                    return saved;
                });
    }

    private String normalizeUrl(String url) {

        if (url == null || url.isBlank())
            return "";

        url = url.trim().toLowerCase(Locale.ROOT);

        if (!url.startsWith("/"))
            url = "/" + url;

        return url;
    }

    private String normalizePermission(String permission) {

        if (permission == null || permission.isBlank()) {
            return null;
        }

        return permission.trim().toUpperCase(Locale.ROOT);
    }
}
